### ISSUE TITLE
Add support for adaptive sampling

### ISSUE THREAD

**Issue by kronosapiens** [zaratanDotWorld/powerRanker#2]
## Motivation

For any set of `n` items, there are `O(n^2) = n(n-1)/2` possible pairs. As `n` grows, the number of pairs grows quadratically, creating a large space over which we must allocate limited voter attention. Without supporting solutions, power ranking becomes infeasible for high `n`.

One possible solution is to implement a process of "adaptive sampling" by which pairs are shown not randomly from the entire set, but _adaptively_ based on knowledge of prior votes and where voter attention will be the highest leverage.

To do this, we calculate an "confidence" for every pair, indicating how confident we are about which of the two pairs is preferred. When showing pairs to users, we select pairs with low confidence scores first. Through this process, we are continuously maximizing average confidence among all pairs ("maximizing certainty") with a minimum of voter attention.

## Implementation

We will define a "confidence score" as follows:

```
  function confidence(a, b) {
    const max = Math.max(a, b);
    const skew = max / (a + b);
    return max * skew;
  }
```

This function has the following properties:

- Pairs with more total votes will have a higher confidence
- Pairs with a higher skew will have a higher confidence

We can calculate the confidence for any pair in `O(1)` time, and draw pairs randomly with a probability based on `1 / confidence`, this preferring pairs for which we are less confident.

**Comment by kronosapiens** [comment]
Note: may potentially be able to use the entropy of a Bernoulli distribution instead of the current confidence score.

**Comment by johnwarden** [comment]
Maybe it should be the entropy of the Beta distribution, since the Beta distribution would represent our beliefs about the fraction of users that prefer one option. The prior could be a Uniform prior or better one of the other priors described in [this paper](https://www.researchgate.net/figure/Illustrations-of-Bayes-prior-Jeffreys-prior-Haldanes-prior-and-the-symmetric-Beta_fig1_340042592), such as Beta(0.5, 0.5).

Then again, I bet the formula produces similar results, and is simpler!

**Comment by johnwarden** [comment]
Hmm, so it occurs to me is that we want to prioritize sampling pairs that minimize overall uncertainty about the final scores. Since you are using an Eigenvector approach (transitive preferences), then if you have a lot of certainty about (A,B), and a lot of certainty about (B,C), but no data for (A,C), we still still be fairly certain about your score (A,C).

Alternatively, suppose we have a lot of certainty about (A,B) and a lot for (C,D), but little for (B,C), then it seems getting a sample for (B,C) has very high information value because it not only directly increases uncertainty for (B,C), it indirectly decreases uncertainty about (A,B), (A,D), and (B,C).

**Comment by kronosapiens** [comment]
That's an interesting point -- a pair reduces uncertainty not only for itself, but potentially for the pairs around it -- specifically, we could look at the uncertainty of all neighboring pairs, or more generally, integrate across the entire graph. Likely more computationally involved, but worth exploring.

For the per-pair score, @johnwarden you are exactly right that the entropy of the posterior Beta distribution would be the best choice, as it most directly models the quantity we care about -- the uncertainty of our data.

That said, calculating the entropy for a Beta distribution is not trivial, involving numerical approximations of the digamma function, etc.

As an alternative, we could use the _variance_ of the posterior Beta. This also points us towards the uncertainty of our data, and is much simpler to calculate. It's not quite as correct of a model in general, but in the case of a Beta distribution over (0,1) I think it works out to basically the same thing.

The implementation would be:

```
  (a * b) /
      ((a + b + 1) * (a + b) ** 2);
```

With `a` and `b` being the number of observations of that option plus 1, representing the prior.

**Comment by kronosapiens** [comment]
![entropy-variance](https://github.com/user-attachments/assets/55f0bb4f-4308-468a-9605-da1c7f06f50a)

I was curious about this, so I had ChatGPT plot comparative diagrams of entropy and variance for a Beta distribution.

Seems for the simple bivariate case of the Beta distribution, they reflect very similar underlying relationships.
